name: Feature Branch CI

on:
  push:
    branches:
      - feature/**
      - fix
      - hotfix
  pull_request:
    branches:
      - main
      - develop
      - fix
      - hotfix

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Create and configure application.yml
        run: |
          echo "${{ secrets.APPLICATION_YML }}" > baebae-BE/src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_DEPLOY_YML }}" > baebae-BE/src/main/resources/application-deploy.yml

      - name: Build with Gradle
        run: |
          cd baebae-BE
          chmod +x ./gradlew
          ./gradlew build --info