name: Spring CI with Deployment to Naver Cloud

on:
  push:
    branches:
      - feature/ci/#9
  pull_request:
    branches:
      - feature/ci/#9

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        run: |
          ls
          cd baebae-Be 
          ls
          ./gradlew build

      - name: Create deployment package
        run: |
          zip -r deployment-package.zip build/libs/*.jar

      - name: Upload deployment package
        uses: actions/upload-artifact@v2
        with:
          name: deployment-package
          path: deployment-package.zip
