name: Feature Branch CI

on:
  push:
    branches:
      - main

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Create and configure application.yml
        run: |
          echo "${{ secrets.APPLICATION_YML }}" > baebae-BE/src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_DEPLOY_YML }}" > baebae-BE/src/main/resources/application-deploy.yml

      - name: Create firebase-admin-sdk file
        run: |
          echo "${{ secrets.FCM_CERTIFICATION }}" > baebae-BE/src/main/resources/baebae-ff525-firebase-adminsdk-zbc8h-7fd10e518b.json

      - name: Build with Gradle
        run: |
          cd baebae-BE
          chmod +x ./gradlew
          ./gradlew build

      - name: Create deployment package
        run: |
          zip -r deploy-package.zip baebae-BE/build/libs/baebae-BE-0.0.1-SNAPSHOT.jar

      - name: Configure AWS CLI && Upload file to Object Storage
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.NAVER_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.NAVER_SECRET_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'
        run: |
          aws --endpoint-url=https://kr.object.ncloudstorage.com s3 cp deploy-package.zip s3://baebae-bucket/deploy-package --content-type application/zip

      - name: Start Deploy Using SourceDeploy
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          STAGE_ID: ${{ secrets.STAGE_ID }}
          SCENARIO_ID: ${{ secrets.SCENARIO_ID }}
          ACCESS_KEY: ${{ secrets.NAVER_ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.NAVER_SECRET_KEY }}
        run: |
          cd baebae-BE
          chmod +x request_source_deploy_start.sh
          ./request_source_deploy_start.sh

